apiVersion: v1
kind: ConfigMap
metadata:
  name: nsq-traefik-consumer
  namespace: prod
data:
  config.yaml: |
    LogLevel: warning
    Nsq:
      Addresses:
          - http://nsqlookupd1.res.k8s.wikia.net
          - http://nsqlookupd2.res.k8s.wikia.net
      Topic: logstash-k8s
      Channel: logstash-k8s-influx-consumers
      MaxInFlight: 200
    Kubernetes:
      AnnotationKey: wikia_com/keys
    InfluxDB:
      Address: http://prod.app-metrics-db.service.sjc.consul:8086
      Database: ingress
      SendInterval: 5s
      Measurement: access_logs
      RetentionPolicy: default
      BatchSize: 100
    Fields:
      - client_host
      - client_username
      - request_method
      - request_path
      - request_protocol
      - origin_status
      - origin_content_size
      - request__referer
      - request__useragent
      - request_count
      - backend_url
      - duration
    Rules:
      - Id: helios
        FrontendRegexp: ^[^\.]+\.k8s\.wikia\.net/helios
        Sampling: 1.0
      - Id: helios-legacy
        FrontendRegexp: ^services\.wikia\.com/auth
        Sampling: 1.0
      - Id: helios-dev-legacy
        FrontendRegexp: ^services\.wikia-dev\.(pl|us)/auth
        Sampling: 1.0
      - Id: helios-dev-k8s
        FrontendRegexp: ^services-k8s\.wikia-dev\.(pl|us)/helios
        Sampling: 1.0
      - Id: helios-dev-k8s
        FrontendRegexp: ^prod\.res\.k8s\.wikia\.net/helios
        Sampling: 1.0
      - Id: services-all
        FrontendRegexp: ^.+\.k8s\.wikia\.net/
        Sampling: 1.0