apiVersion: v1
kind: ConfigMap
metadata:
  name: nsq-traefik-consumer
  namespace: dev
data:
  config.yaml: |
    LogLevel: warning
    Nsq:
      Addresses:
          - http://nsqlookupd1.poz-dev.k8s.wikia.net
          - http://nsqlookupd2.poz-dev.k8s.wikia.net
      Topic: logstash-k8s
      Channel: logstash-k8s-influx-consumers
      MaxInFlight: 200
    Kubernetes:
      AnnotationKey: wikia_com/keys
    InfluxDB:
      Address: http://dev.app-metrics-db.service.poz-dev.consul:8086
      Database: ingress
      SendInterval: 5s
      Measurement: access_logs
      RetentionPolicy: default
      BatchSize: 100
    Fields:
      - duration
      - backend_url.Host
      - backend_url.Path
      - backend_address
      - client_address
      - client_host
      - client_port
      - client_username
      - request_address
      - request_host
      - request_port
      - request_method
      - request_path
      - request_protocol
    #  - request_line
      - request_content_size
      - origin_duration
      - origin_content_size
      - origin_status
    #  - origin_status_line
      - downstream_status
    #  - downstream_status_line
      - downstream_content_size
      - request_count
      - gzip_ratio
      - overhead
      - retry_attempts
      - original_timestamp
      - request__referer
      - request__user-agent
    Rules:
      - Id: helios-internal
        FrontendRegexp: ^[^\.]+\.k8s\.wikia\.net/helios
        Sampling: 0.5
      - Id: helios
        FrontendRegexp: ^services\.wikia-dev\.pl/auth
        Sampling: 0.5
      - Id: helios
        FrontendRegexp: ^services-k8s\.wikia-dev\.pl/helios
        Sampling: 0.5
      - Id: services-all
        FrontendRegexp: ^services\.wikia-dev\.pl
        Sampling: 0.5
      - Id: services-all
        FrontendRegexp: ^services-k8s\.wikia-dev\.pl
        Sampling: 0.5
      - Id: services-all-internal
        FrontendRegexp: ^poz-dev\.k8s\.wikia\.net
        Sampling: 0.5
      - Id: services-all-internal
        FrontendRegexp: ^dev\.poz-dev\.k8s\.wikia\.net
        Sampling: 0.5
