apiVersion: v1
kind: ConfigMap
metadata:
  name: nsq-traefik-consumer
  namespace: prod
data:
  config.yaml: |
    LogLevel: warning
    Nsq:
      Addresses:
          - http://nsqlookupd1.res.k8s.wikia.net
          - http://nsqlookupd2.res.k8s.wikia.net
      Topic: logstash-k8s
      Channel: logstash-k8s-influx-consumers
      MaxInFlight: 200
    Kubernetes:
      AnnotationKey: wikia_com/keys
    InfluxDB:
      Address: http://prod.app-metrics-db.service.sjc.consul:8086
      Database: ingress
      SendInterval: 5s
      Measurement: access_logs
      RetentionPolicy: default
      BatchSize: 100
    Rules:
      - Id: services-all
        FrontendRegexp: ^.+\.k8s\.wikia\.net/
        SamplingRate: 1.0
      - Id: helios
        FrontendRegexp: ^[^\.]+\.k8s\.wikia\.net/helios
        SamplingRate: 1.0
      - Id: helios-legacy
        FrontendRegexp: ^services\.wikia\.com/auth
        SamplingRate: 1.0
      - Id: helios-dev-legacy
        FrontendRegexp: ^services\.wikia-dev\.(pl|us)/auth
        SamplingRate: 1.0
      - Id: helios-dev-k8s
        FrontendRegexp: ^services-k8s\.wikia-dev\.(pl|us)/helios
        SamplingRate: 1.0
      - Id: helios-dev-k8s
        FrontendRegexp: ^prod\.res\.k8s\.wikia\.net/helios
        SamplingRate: 1.0
