apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nsq-traefik-consumer
  namespace: prod
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nsq-traefik-consumer
    spec:
      containers:
      - name: nsq-traefik-consumer
      #TODO proper versioning!!!!!!
        image: artifactory.wikia-inc.com/platform/nsq-traefik-consumer:v0.6.0
        args: ["--config", "/etc/nsq-traefik-consumer/config.yaml", "run"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nsq-traefik-consumer
        resources:
          limits:
            memory: 300Mi
          requests:
            cpu: 500m
            memory: 300Mi
        env:
        - name: HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBERNETES_POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumes:
        - name: config-volume
          configMap:
            name: nsq-traefik-consumer