apiVersion: v1
kind: Service
metadata:
  labels:
    app: nsq-traefik-consumer
  name: nsq-traefik-consumer
  namespace: prod
spec:
  selector:
    app: nsq-traefik-consumer
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nsq-traefik-consumer
  namespace: prod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nsq-traefik-consumer
    spec:
      containers:
      - name: nsq-traefik-consumer
      #TODO proper versioning!!!!!!
        image: artifactory.wikia-inc.com/platform/nsq-traefik-consumer:v0.1.0
        livenessProbe:
          httpGet:
            path: /heartbeat
            port: 9500
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 20
        resources:
          limits:
            memory: 300Mi
          requests:
            cpu: 500m
            memory: 300Mi
        env:
        - name: HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBERNETES_POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
